# Generated by Django 3.2.3 on 2021-10-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0007_alter_contactmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('New', 'New'), ('Closed', 'Closed')], default='New', max_length=40),
        ),
    ]
