# Generated by Django 3.2.3 on 2021-10-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0010_alter_contactmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Closed', 'Closed'), ('Read', 'Read')], default='New', max_length=40),
        ),
    ]
