# Generated by Django 3.2.3 on 2021-10-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_APP', '0002_oderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oderproduct',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
